import pygame

FRAMERATE = 600
DELTA = 1.0/FRAMERATE
FRAME_NAME = 'Billiards Simulation'
FONT = 'Calibri'

WIDTH = 1100
HEIGHT = WIDTH / 1.8
SIDE_WIDTH = WIDTH * 0.055

RADIUS = 14
POCKET_RADIUS = 45
POCKET_DIAM = 2*POCKET_RADIUS
SIDE_POCKET_RADIUS = 30
POCKETS_VISIBLE = False

TRIANGLE_SPACING = 30
TRIANGLE_SIZE = 5

X_BUMPER_RANGES = [
    (POCKET_DIAM, 0.5 * WIDTH - SIDE_POCKET_RADIUS), 
    (0.5 * WIDTH + SIDE_POCKET_RADIUS, WIDTH - POCKET_DIAM)
]
Y_BUMPER_RANGES = [
    (POCKET_DIAM, HEIGHT-POCKET_DIAM)
]

G = -9.8
FRICTION = 0.1 * (FRAMERATE / 100)
CONST_RESTITUTION_RAIL = 0.7
CONST_RESTITUTION_BALL = 0.9


